install:
  - composer install --dev
script:
  - vendor/bin/php-cs-fixer --diff --dry-run --verbose fix
  - vendor/bin/phpunit
language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
